version: '3'

services:
    # Контейнер для приложения Laravel, который мы настроили в Dockerfile выше
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: basket-shop
        container_name: basket-shop
        restart: unless-stopped
        volumes:
            - .:/var/www/html
        environment:
            - DB_HOST=mysql
            - DB_PORT=3306
            - DB_DATABASE=basket_shop
            - DB_USERNAME=root
            - DB_PASSWORD=AbuMalik333
        depends_on:
            - mysql
        networks:
            - app-network

    # Контейнер для базы данных MySQL
    mysql:
        image: mysql:8.0
        container_name: basket-shop-mysql
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: basket_shop
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: root
            MYSQL_PASSWORD: AbuMalik333
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - app-network

volumes:
    mysql-data:

networks:
    app-network:
        driver: bridge
